language: node_js
os: linux

node_js:
  - 14

branches:
  only:
    - master

jobs:
  include:
    - stage: build
      name: Lint
      script: npm run lint
    
    - script: npm run compile
      name: Compile

    - script: npm run test
      name: Test
