language: node_js
os: linux

node_js:
  - 14

branches:
  only:
    - master

jobs:
  include:
    - stage: build
      name: Lint
      script: npm run lint
    
    - script: npm run compile
      name: Compile

    - stage: test
      name: Unit tests
      script:
        - npm run test
        - npm run coveralls
