version: '3.1'

services:
  postgres:
    image: postgres:11-alpine
    container_name: dev_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
